// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.ifc_ar_core

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_ifc_ar_core_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_ifc_ar_core_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "ifc_ar_core"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}




































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            System.loadLibrary("ifc_ar_core")
            loadIndirect<UniffiLib>(componentName = "ifc_ar_core")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
        
    }

    fun uniffi_ifc_ar_core_fn_func_create_wall_mesh(`startX`: Float,`startZ`: Float,`endX`: Float,`endZ`: Float,`height`: Float,`thickness`: Float,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ifc_ar_core_fn_func_export_combined_ifc(`roomData`: RustBuffer.ByValue,`fixtures`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ifc_ar_core_fn_func_export_combined_ifc_with_walls(`roomData`: RustBuffer.ByValue,`fixtures`: RustBuffer.ByValue,`walls`: RustBuffer.ByValue,`deletedElementIds`: RustBuffer.ByValue,`movedElements`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ifc_ar_core_fn_func_parse_and_export_glb(`data`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ifc_ar_core_fn_func_parse_ifc(`data`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_ifc_ar_core_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_ifc_ar_core_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_ifc_ar_core_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_ifc_ar_core_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_ifc_ar_core_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_ifc_ar_core_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_ifc_ar_core_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_ifc_ar_core_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_ifc_ar_core_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_ifc_ar_core_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_ifc_ar_core_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_ifc_ar_core_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_ifc_ar_core_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_ifc_ar_core_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_ifc_ar_core_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_ifc_ar_core_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_ifc_ar_core_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_ifc_ar_core_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_ifc_ar_core_checksum_func_create_wall_mesh(
    ): Short
    fun uniffi_ifc_ar_core_checksum_func_export_combined_ifc(
    ): Short
    fun uniffi_ifc_ar_core_checksum_func_export_combined_ifc_with_walls(
    ): Short
    fun uniffi_ifc_ar_core_checksum_func_parse_and_export_glb(
    ): Short
    fun uniffi_ifc_ar_core_checksum_func_parse_ifc(
    ): Short
    fun ffi_ifc_ar_core_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_ifc_ar_core_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_ifc_ar_core_checksum_func_create_wall_mesh() != 5429.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ifc_ar_core_checksum_func_export_combined_ifc() != 41503.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ifc_ar_core_checksum_func_export_combined_ifc_with_walls() != 40242.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ifc_ar_core_checksum_func_parse_and_export_glb() != 14060.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ifc_ar_core_checksum_func_parse_ifc() != 65195.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterFloat: FfiConverter<Float, Float> {
    override fun lift(value: Float): Float {
        return value
    }

    override fun read(buf: ByteBuffer): Float {
        return buf.getFloat()
    }

    override fun lower(value: Float): Float {
        return value
    }

    override fun allocationSize(value: Float) = 4UL

    override fun write(value: Float, buf: ByteBuffer) {
        buf.putFloat(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}



data class ElementColor (
    var `r`: kotlin.Float, 
    var `g`: kotlin.Float, 
    var `b`: kotlin.Float, 
    var `a`: kotlin.Float
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeElementColor: FfiConverterRustBuffer<ElementColor> {
    override fun read(buf: ByteBuffer): ElementColor {
        return ElementColor(
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
        )
    }

    override fun allocationSize(value: ElementColor) = (
            FfiConverterFloat.allocationSize(value.`r`) +
            FfiConverterFloat.allocationSize(value.`g`) +
            FfiConverterFloat.allocationSize(value.`b`) +
            FfiConverterFloat.allocationSize(value.`a`)
    )

    override fun write(value: ElementColor, buf: ByteBuffer) {
            FfiConverterFloat.write(value.`r`, buf)
            FfiConverterFloat.write(value.`g`, buf)
            FfiConverterFloat.write(value.`b`, buf)
            FfiConverterFloat.write(value.`a`, buf)
    }
}



data class ElementMoveInput (
    var `elementId`: kotlin.ULong, 
    var `offsetX`: kotlin.Float, 
    var `offsetY`: kotlin.Float, 
    var `offsetZ`: kotlin.Float
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeElementMoveInput: FfiConverterRustBuffer<ElementMoveInput> {
    override fun read(buf: ByteBuffer): ElementMoveInput {
        return ElementMoveInput(
            FfiConverterULong.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
        )
    }

    override fun allocationSize(value: ElementMoveInput) = (
            FfiConverterULong.allocationSize(value.`elementId`) +
            FfiConverterFloat.allocationSize(value.`offsetX`) +
            FfiConverterFloat.allocationSize(value.`offsetY`) +
            FfiConverterFloat.allocationSize(value.`offsetZ`)
    )

    override fun write(value: ElementMoveInput, buf: ByteBuffer) {
            FfiConverterULong.write(value.`elementId`, buf)
            FfiConverterFloat.write(value.`offsetX`, buf)
            FfiConverterFloat.write(value.`offsetY`, buf)
            FfiConverterFloat.write(value.`offsetZ`, buf)
    }
}



data class FixtureExportInput (
    var `ifcData`: kotlin.ByteArray, 
    var `relX`: kotlin.Float, 
    var `relY`: kotlin.Float, 
    var `relZ`: kotlin.Float, 
    var `rotationY`: kotlin.Float
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFixtureExportInput: FfiConverterRustBuffer<FixtureExportInput> {
    override fun read(buf: ByteBuffer): FixtureExportInput {
        return FixtureExportInput(
            FfiConverterByteArray.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
        )
    }

    override fun allocationSize(value: FixtureExportInput) = (
            FfiConverterByteArray.allocationSize(value.`ifcData`) +
            FfiConverterFloat.allocationSize(value.`relX`) +
            FfiConverterFloat.allocationSize(value.`relY`) +
            FfiConverterFloat.allocationSize(value.`relZ`) +
            FfiConverterFloat.allocationSize(value.`rotationY`)
    )

    override fun write(value: FixtureExportInput, buf: ByteBuffer) {
            FfiConverterByteArray.write(value.`ifcData`, buf)
            FfiConverterFloat.write(value.`relX`, buf)
            FfiConverterFloat.write(value.`relY`, buf)
            FfiConverterFloat.write(value.`relZ`, buf)
            FfiConverterFloat.write(value.`rotationY`, buf)
    }
}



data class IfcClassificationInfo (
    var `name`: kotlin.String, 
    var `systemName`: kotlin.String, 
    var `systemSource`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeIfcClassificationInfo: FfiConverterRustBuffer<IfcClassificationInfo> {
    override fun read(buf: ByteBuffer): IfcClassificationInfo {
        return IfcClassificationInfo(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: IfcClassificationInfo) = (
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`systemName`) +
            FfiConverterOptionalString.allocationSize(value.`systemSource`)
    )

    override fun write(value: IfcClassificationInfo, buf: ByteBuffer) {
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`systemName`, buf)
            FfiConverterOptionalString.write(value.`systemSource`, buf)
    }
}



data class IfcElement (
    var `id`: kotlin.ULong, 
    var `ifcType`: kotlin.String, 
    var `name`: kotlin.String?, 
    var `globalId`: kotlin.String?, 
    var `description`: kotlin.String?, 
    var `objectType`: kotlin.String?, 
    var `tag`: kotlin.String?, 
    var `predefinedType`: kotlin.String?, 
    var `color`: ElementColor, 
    var `geometry`: MeshData?, 
    var `properties`: List<IfcProperty>, 
    var `quantities`: List<IfcQuantity>, 
    var `material`: IfcMaterialInfo?, 
    var `typeInfo`: IfcTypeInfo?, 
    var `classification`: IfcClassificationInfo?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeIfcElement: FfiConverterRustBuffer<IfcElement> {
    override fun read(buf: ByteBuffer): IfcElement {
        return IfcElement(
            FfiConverterULong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterTypeElementColor.read(buf),
            FfiConverterOptionalTypeMeshData.read(buf),
            FfiConverterSequenceTypeIfcProperty.read(buf),
            FfiConverterSequenceTypeIfcQuantity.read(buf),
            FfiConverterOptionalTypeIfcMaterialInfo.read(buf),
            FfiConverterOptionalTypeIfcTypeInfo.read(buf),
            FfiConverterOptionalTypeIfcClassificationInfo.read(buf),
        )
    }

    override fun allocationSize(value: IfcElement) = (
            FfiConverterULong.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`ifcType`) +
            FfiConverterOptionalString.allocationSize(value.`name`) +
            FfiConverterOptionalString.allocationSize(value.`globalId`) +
            FfiConverterOptionalString.allocationSize(value.`description`) +
            FfiConverterOptionalString.allocationSize(value.`objectType`) +
            FfiConverterOptionalString.allocationSize(value.`tag`) +
            FfiConverterOptionalString.allocationSize(value.`predefinedType`) +
            FfiConverterTypeElementColor.allocationSize(value.`color`) +
            FfiConverterOptionalTypeMeshData.allocationSize(value.`geometry`) +
            FfiConverterSequenceTypeIfcProperty.allocationSize(value.`properties`) +
            FfiConverterSequenceTypeIfcQuantity.allocationSize(value.`quantities`) +
            FfiConverterOptionalTypeIfcMaterialInfo.allocationSize(value.`material`) +
            FfiConverterOptionalTypeIfcTypeInfo.allocationSize(value.`typeInfo`) +
            FfiConverterOptionalTypeIfcClassificationInfo.allocationSize(value.`classification`)
    )

    override fun write(value: IfcElement, buf: ByteBuffer) {
            FfiConverterULong.write(value.`id`, buf)
            FfiConverterString.write(value.`ifcType`, buf)
            FfiConverterOptionalString.write(value.`name`, buf)
            FfiConverterOptionalString.write(value.`globalId`, buf)
            FfiConverterOptionalString.write(value.`description`, buf)
            FfiConverterOptionalString.write(value.`objectType`, buf)
            FfiConverterOptionalString.write(value.`tag`, buf)
            FfiConverterOptionalString.write(value.`predefinedType`, buf)
            FfiConverterTypeElementColor.write(value.`color`, buf)
            FfiConverterOptionalTypeMeshData.write(value.`geometry`, buf)
            FfiConverterSequenceTypeIfcProperty.write(value.`properties`, buf)
            FfiConverterSequenceTypeIfcQuantity.write(value.`quantities`, buf)
            FfiConverterOptionalTypeIfcMaterialInfo.write(value.`material`, buf)
            FfiConverterOptionalTypeIfcTypeInfo.write(value.`typeInfo`, buf)
            FfiConverterOptionalTypeIfcClassificationInfo.write(value.`classification`, buf)
    }
}



data class IfcMaterialInfo (
    var `name`: kotlin.String, 
    var `category`: kotlin.String?, 
    var `layers`: List<IfcMaterialLayer>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeIfcMaterialInfo: FfiConverterRustBuffer<IfcMaterialInfo> {
    override fun read(buf: ByteBuffer): IfcMaterialInfo {
        return IfcMaterialInfo(
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterSequenceTypeIfcMaterialLayer.read(buf),
        )
    }

    override fun allocationSize(value: IfcMaterialInfo) = (
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterOptionalString.allocationSize(value.`category`) +
            FfiConverterSequenceTypeIfcMaterialLayer.allocationSize(value.`layers`)
    )

    override fun write(value: IfcMaterialInfo, buf: ByteBuffer) {
            FfiConverterString.write(value.`name`, buf)
            FfiConverterOptionalString.write(value.`category`, buf)
            FfiConverterSequenceTypeIfcMaterialLayer.write(value.`layers`, buf)
    }
}



data class IfcMaterialLayer (
    var `materialName`: kotlin.String, 
    var `thickness`: kotlin.Double?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeIfcMaterialLayer: FfiConverterRustBuffer<IfcMaterialLayer> {
    override fun read(buf: ByteBuffer): IfcMaterialLayer {
        return IfcMaterialLayer(
            FfiConverterString.read(buf),
            FfiConverterOptionalDouble.read(buf),
        )
    }

    override fun allocationSize(value: IfcMaterialLayer) = (
            FfiConverterString.allocationSize(value.`materialName`) +
            FfiConverterOptionalDouble.allocationSize(value.`thickness`)
    )

    override fun write(value: IfcMaterialLayer, buf: ByteBuffer) {
            FfiConverterString.write(value.`materialName`, buf)
            FfiConverterOptionalDouble.write(value.`thickness`, buf)
    }
}



data class IfcModel (
    var `elements`: List<IfcElement>, 
    var `spatialTree`: SpatialTree, 
    var `bounds`: ModelBounds
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeIfcModel: FfiConverterRustBuffer<IfcModel> {
    override fun read(buf: ByteBuffer): IfcModel {
        return IfcModel(
            FfiConverterSequenceTypeIfcElement.read(buf),
            FfiConverterTypeSpatialTree.read(buf),
            FfiConverterTypeModelBounds.read(buf),
        )
    }

    override fun allocationSize(value: IfcModel) = (
            FfiConverterSequenceTypeIfcElement.allocationSize(value.`elements`) +
            FfiConverterTypeSpatialTree.allocationSize(value.`spatialTree`) +
            FfiConverterTypeModelBounds.allocationSize(value.`bounds`)
    )

    override fun write(value: IfcModel, buf: ByteBuffer) {
            FfiConverterSequenceTypeIfcElement.write(value.`elements`, buf)
            FfiConverterTypeSpatialTree.write(value.`spatialTree`, buf)
            FfiConverterTypeModelBounds.write(value.`bounds`, buf)
    }
}



data class IfcProperty (
    var `name`: kotlin.String, 
    var `value`: kotlin.String, 
    var `propertySet`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeIfcProperty: FfiConverterRustBuffer<IfcProperty> {
    override fun read(buf: ByteBuffer): IfcProperty {
        return IfcProperty(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: IfcProperty) = (
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`value`) +
            FfiConverterOptionalString.allocationSize(value.`propertySet`)
    )

    override fun write(value: IfcProperty, buf: ByteBuffer) {
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`value`, buf)
            FfiConverterOptionalString.write(value.`propertySet`, buf)
    }
}



data class IfcQuantity (
    var `name`: kotlin.String, 
    var `value`: kotlin.Double, 
    var `quantityType`: kotlin.String, 
    var `quantitySet`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeIfcQuantity: FfiConverterRustBuffer<IfcQuantity> {
    override fun read(buf: ByteBuffer): IfcQuantity {
        return IfcQuantity(
            FfiConverterString.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: IfcQuantity) = (
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterDouble.allocationSize(value.`value`) +
            FfiConverterString.allocationSize(value.`quantityType`) +
            FfiConverterOptionalString.allocationSize(value.`quantitySet`)
    )

    override fun write(value: IfcQuantity, buf: ByteBuffer) {
            FfiConverterString.write(value.`name`, buf)
            FfiConverterDouble.write(value.`value`, buf)
            FfiConverterString.write(value.`quantityType`, buf)
            FfiConverterOptionalString.write(value.`quantitySet`, buf)
    }
}



data class IfcTypeInfo (
    var `ifcType`: kotlin.String, 
    var `name`: kotlin.String?, 
    var `predefinedType`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeIfcTypeInfo: FfiConverterRustBuffer<IfcTypeInfo> {
    override fun read(buf: ByteBuffer): IfcTypeInfo {
        return IfcTypeInfo(
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: IfcTypeInfo) = (
            FfiConverterString.allocationSize(value.`ifcType`) +
            FfiConverterOptionalString.allocationSize(value.`name`) +
            FfiConverterOptionalString.allocationSize(value.`predefinedType`)
    )

    override fun write(value: IfcTypeInfo, buf: ByteBuffer) {
            FfiConverterString.write(value.`ifcType`, buf)
            FfiConverterOptionalString.write(value.`name`, buf)
            FfiConverterOptionalString.write(value.`predefinedType`, buf)
    }
}



data class MeshData (
    var `positions`: List<kotlin.Float>, 
    var `normals`: List<kotlin.Float>, 
    var `indices`: List<kotlin.UInt>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeMeshData: FfiConverterRustBuffer<MeshData> {
    override fun read(buf: ByteBuffer): MeshData {
        return MeshData(
            FfiConverterSequenceFloat.read(buf),
            FfiConverterSequenceFloat.read(buf),
            FfiConverterSequenceUInt.read(buf),
        )
    }

    override fun allocationSize(value: MeshData) = (
            FfiConverterSequenceFloat.allocationSize(value.`positions`) +
            FfiConverterSequenceFloat.allocationSize(value.`normals`) +
            FfiConverterSequenceUInt.allocationSize(value.`indices`)
    )

    override fun write(value: MeshData, buf: ByteBuffer) {
            FfiConverterSequenceFloat.write(value.`positions`, buf)
            FfiConverterSequenceFloat.write(value.`normals`, buf)
            FfiConverterSequenceUInt.write(value.`indices`, buf)
    }
}



data class ModelBounds (
    var `minPoint`: List<kotlin.Float>, 
    var `maxPoint`: List<kotlin.Float>, 
    var `diagonal`: kotlin.Float
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeModelBounds: FfiConverterRustBuffer<ModelBounds> {
    override fun read(buf: ByteBuffer): ModelBounds {
        return ModelBounds(
            FfiConverterSequenceFloat.read(buf),
            FfiConverterSequenceFloat.read(buf),
            FfiConverterFloat.read(buf),
        )
    }

    override fun allocationSize(value: ModelBounds) = (
            FfiConverterSequenceFloat.allocationSize(value.`minPoint`) +
            FfiConverterSequenceFloat.allocationSize(value.`maxPoint`) +
            FfiConverterFloat.allocationSize(value.`diagonal`)
    )

    override fun write(value: ModelBounds, buf: ByteBuffer) {
            FfiConverterSequenceFloat.write(value.`minPoint`, buf)
            FfiConverterSequenceFloat.write(value.`maxPoint`, buf)
            FfiConverterFloat.write(value.`diagonal`, buf)
    }
}



data class SpatialNode (
    var `id`: kotlin.ULong, 
    var `ifcType`: kotlin.String, 
    var `name`: kotlin.String?, 
    var `children`: List<kotlin.ULong>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSpatialNode: FfiConverterRustBuffer<SpatialNode> {
    override fun read(buf: ByteBuffer): SpatialNode {
        return SpatialNode(
            FfiConverterULong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterSequenceULong.read(buf),
        )
    }

    override fun allocationSize(value: SpatialNode) = (
            FfiConverterULong.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`ifcType`) +
            FfiConverterOptionalString.allocationSize(value.`name`) +
            FfiConverterSequenceULong.allocationSize(value.`children`)
    )

    override fun write(value: SpatialNode, buf: ByteBuffer) {
            FfiConverterULong.write(value.`id`, buf)
            FfiConverterString.write(value.`ifcType`, buf)
            FfiConverterOptionalString.write(value.`name`, buf)
            FfiConverterSequenceULong.write(value.`children`, buf)
    }
}



data class SpatialTree (
    var `nodes`: List<SpatialNode>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSpatialTree: FfiConverterRustBuffer<SpatialTree> {
    override fun read(buf: ByteBuffer): SpatialTree {
        return SpatialTree(
            FfiConverterSequenceTypeSpatialNode.read(buf),
        )
    }

    override fun allocationSize(value: SpatialTree) = (
            FfiConverterSequenceTypeSpatialNode.allocationSize(value.`nodes`)
    )

    override fun write(value: SpatialTree, buf: ByteBuffer) {
            FfiConverterSequenceTypeSpatialNode.write(value.`nodes`, buf)
    }
}



data class WallExportInput (
    var `positions`: List<kotlin.Float>, 
    var `normals`: List<kotlin.Float>, 
    var `indices`: List<kotlin.UInt>, 
    var `relX`: kotlin.Float, 
    var `relY`: kotlin.Float, 
    var `relZ`: kotlin.Float, 
    var `height`: kotlin.Float, 
    var `thickness`: kotlin.Float, 
    var `length`: kotlin.Float
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeWallExportInput: FfiConverterRustBuffer<WallExportInput> {
    override fun read(buf: ByteBuffer): WallExportInput {
        return WallExportInput(
            FfiConverterSequenceFloat.read(buf),
            FfiConverterSequenceFloat.read(buf),
            FfiConverterSequenceUInt.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
        )
    }

    override fun allocationSize(value: WallExportInput) = (
            FfiConverterSequenceFloat.allocationSize(value.`positions`) +
            FfiConverterSequenceFloat.allocationSize(value.`normals`) +
            FfiConverterSequenceUInt.allocationSize(value.`indices`) +
            FfiConverterFloat.allocationSize(value.`relX`) +
            FfiConverterFloat.allocationSize(value.`relY`) +
            FfiConverterFloat.allocationSize(value.`relZ`) +
            FfiConverterFloat.allocationSize(value.`height`) +
            FfiConverterFloat.allocationSize(value.`thickness`) +
            FfiConverterFloat.allocationSize(value.`length`)
    )

    override fun write(value: WallExportInput, buf: ByteBuffer) {
            FfiConverterSequenceFloat.write(value.`positions`, buf)
            FfiConverterSequenceFloat.write(value.`normals`, buf)
            FfiConverterSequenceUInt.write(value.`indices`, buf)
            FfiConverterFloat.write(value.`relX`, buf)
            FfiConverterFloat.write(value.`relY`, buf)
            FfiConverterFloat.write(value.`relZ`, buf)
            FfiConverterFloat.write(value.`height`, buf)
            FfiConverterFloat.write(value.`thickness`, buf)
            FfiConverterFloat.write(value.`length`, buf)
    }
}





sealed class IfcArException(message: String): kotlin.Exception(message) {
        
        class ParseException(message: String) : IfcArException(message)
        
        class GeometryException(message: String) : IfcArException(message)
        
        class GltfExportException(message: String) : IfcArException(message)
        
        class InvalidInput(message: String) : IfcArException(message)
        

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<IfcArException> {
        override fun lift(error_buf: RustBuffer.ByValue): IfcArException = FfiConverterTypeIfcArError.lift(error_buf)
    }
}

/**
 * @suppress
 */
public object FfiConverterTypeIfcArError : FfiConverterRustBuffer<IfcArException> {
    override fun read(buf: ByteBuffer): IfcArException {
        
            return when(buf.getInt()) {
            1 -> IfcArException.ParseException(FfiConverterString.read(buf))
            2 -> IfcArException.GeometryException(FfiConverterString.read(buf))
            3 -> IfcArException.GltfExportException(FfiConverterString.read(buf))
            4 -> IfcArException.InvalidInput(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
        
    }

    override fun allocationSize(value: IfcArException): ULong {
        return 4UL
    }

    override fun write(value: IfcArException, buf: ByteBuffer) {
        when(value) {
            is IfcArException.ParseException -> {
                buf.putInt(1)
                Unit
            }
            is IfcArException.GeometryException -> {
                buf.putInt(2)
                Unit
            }
            is IfcArException.GltfExportException -> {
                buf.putInt(3)
                Unit
            }
            is IfcArException.InvalidInput -> {
                buf.putInt(4)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalDouble: FfiConverterRustBuffer<kotlin.Double?> {
    override fun read(buf: ByteBuffer): kotlin.Double? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterDouble.read(buf)
    }

    override fun allocationSize(value: kotlin.Double?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterDouble.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Double?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterDouble.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeIfcClassificationInfo: FfiConverterRustBuffer<IfcClassificationInfo?> {
    override fun read(buf: ByteBuffer): IfcClassificationInfo? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeIfcClassificationInfo.read(buf)
    }

    override fun allocationSize(value: IfcClassificationInfo?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeIfcClassificationInfo.allocationSize(value)
        }
    }

    override fun write(value: IfcClassificationInfo?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeIfcClassificationInfo.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeIfcMaterialInfo: FfiConverterRustBuffer<IfcMaterialInfo?> {
    override fun read(buf: ByteBuffer): IfcMaterialInfo? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeIfcMaterialInfo.read(buf)
    }

    override fun allocationSize(value: IfcMaterialInfo?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeIfcMaterialInfo.allocationSize(value)
        }
    }

    override fun write(value: IfcMaterialInfo?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeIfcMaterialInfo.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeIfcTypeInfo: FfiConverterRustBuffer<IfcTypeInfo?> {
    override fun read(buf: ByteBuffer): IfcTypeInfo? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeIfcTypeInfo.read(buf)
    }

    override fun allocationSize(value: IfcTypeInfo?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeIfcTypeInfo.allocationSize(value)
        }
    }

    override fun write(value: IfcTypeInfo?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeIfcTypeInfo.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeMeshData: FfiConverterRustBuffer<MeshData?> {
    override fun read(buf: ByteBuffer): MeshData? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeMeshData.read(buf)
    }

    override fun allocationSize(value: MeshData?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeMeshData.allocationSize(value)
        }
    }

    override fun write(value: MeshData?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeMeshData.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceUInt: FfiConverterRustBuffer<List<kotlin.UInt>> {
    override fun read(buf: ByteBuffer): List<kotlin.UInt> {
        val len = buf.getInt()
        return List<kotlin.UInt>(len) {
            FfiConverterUInt.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.UInt>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterUInt.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.UInt>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterUInt.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceULong: FfiConverterRustBuffer<List<kotlin.ULong>> {
    override fun read(buf: ByteBuffer): List<kotlin.ULong> {
        val len = buf.getInt()
        return List<kotlin.ULong>(len) {
            FfiConverterULong.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.ULong>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterULong.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.ULong>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterULong.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceFloat: FfiConverterRustBuffer<List<kotlin.Float>> {
    override fun read(buf: ByteBuffer): List<kotlin.Float> {
        val len = buf.getInt()
        return List<kotlin.Float>(len) {
            FfiConverterFloat.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.Float>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterFloat.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.Float>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterFloat.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeElementMoveInput: FfiConverterRustBuffer<List<ElementMoveInput>> {
    override fun read(buf: ByteBuffer): List<ElementMoveInput> {
        val len = buf.getInt()
        return List<ElementMoveInput>(len) {
            FfiConverterTypeElementMoveInput.read(buf)
        }
    }

    override fun allocationSize(value: List<ElementMoveInput>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeElementMoveInput.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<ElementMoveInput>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeElementMoveInput.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFixtureExportInput: FfiConverterRustBuffer<List<FixtureExportInput>> {
    override fun read(buf: ByteBuffer): List<FixtureExportInput> {
        val len = buf.getInt()
        return List<FixtureExportInput>(len) {
            FfiConverterTypeFixtureExportInput.read(buf)
        }
    }

    override fun allocationSize(value: List<FixtureExportInput>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFixtureExportInput.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FixtureExportInput>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFixtureExportInput.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeIfcElement: FfiConverterRustBuffer<List<IfcElement>> {
    override fun read(buf: ByteBuffer): List<IfcElement> {
        val len = buf.getInt()
        return List<IfcElement>(len) {
            FfiConverterTypeIfcElement.read(buf)
        }
    }

    override fun allocationSize(value: List<IfcElement>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeIfcElement.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<IfcElement>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeIfcElement.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeIfcMaterialLayer: FfiConverterRustBuffer<List<IfcMaterialLayer>> {
    override fun read(buf: ByteBuffer): List<IfcMaterialLayer> {
        val len = buf.getInt()
        return List<IfcMaterialLayer>(len) {
            FfiConverterTypeIfcMaterialLayer.read(buf)
        }
    }

    override fun allocationSize(value: List<IfcMaterialLayer>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeIfcMaterialLayer.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<IfcMaterialLayer>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeIfcMaterialLayer.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeIfcProperty: FfiConverterRustBuffer<List<IfcProperty>> {
    override fun read(buf: ByteBuffer): List<IfcProperty> {
        val len = buf.getInt()
        return List<IfcProperty>(len) {
            FfiConverterTypeIfcProperty.read(buf)
        }
    }

    override fun allocationSize(value: List<IfcProperty>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeIfcProperty.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<IfcProperty>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeIfcProperty.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeIfcQuantity: FfiConverterRustBuffer<List<IfcQuantity>> {
    override fun read(buf: ByteBuffer): List<IfcQuantity> {
        val len = buf.getInt()
        return List<IfcQuantity>(len) {
            FfiConverterTypeIfcQuantity.read(buf)
        }
    }

    override fun allocationSize(value: List<IfcQuantity>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeIfcQuantity.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<IfcQuantity>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeIfcQuantity.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeSpatialNode: FfiConverterRustBuffer<List<SpatialNode>> {
    override fun read(buf: ByteBuffer): List<SpatialNode> {
        val len = buf.getInt()
        return List<SpatialNode>(len) {
            FfiConverterTypeSpatialNode.read(buf)
        }
    }

    override fun allocationSize(value: List<SpatialNode>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeSpatialNode.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<SpatialNode>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeSpatialNode.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeWallExportInput: FfiConverterRustBuffer<List<WallExportInput>> {
    override fun read(buf: ByteBuffer): List<WallExportInput> {
        val len = buf.getInt()
        return List<WallExportInput>(len) {
            FfiConverterTypeWallExportInput.read(buf)
        }
    }

    override fun allocationSize(value: List<WallExportInput>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeWallExportInput.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<WallExportInput>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeWallExportInput.write(it, buf)
        }
    }
} fun `createWallMesh`(`startX`: kotlin.Float, `startZ`: kotlin.Float, `endX`: kotlin.Float, `endZ`: kotlin.Float, `height`: kotlin.Float, `thickness`: kotlin.Float): IfcElement {
            return FfiConverterTypeIfcElement.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_ifc_ar_core_fn_func_create_wall_mesh(
        FfiConverterFloat.lower(`startX`),FfiConverterFloat.lower(`startZ`),FfiConverterFloat.lower(`endX`),FfiConverterFloat.lower(`endZ`),FfiConverterFloat.lower(`height`),FfiConverterFloat.lower(`thickness`),_status)
}
    )
    }
    

    @Throws(IfcArException::class) fun `exportCombinedIfc`(`roomData`: kotlin.ByteArray, `fixtures`: List<FixtureExportInput>): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(IfcArException) { _status ->
    UniffiLib.INSTANCE.uniffi_ifc_ar_core_fn_func_export_combined_ifc(
        FfiConverterByteArray.lower(`roomData`),FfiConverterSequenceTypeFixtureExportInput.lower(`fixtures`),_status)
}
    )
    }
    

    @Throws(IfcArException::class) fun `exportCombinedIfcWithWalls`(`roomData`: kotlin.ByteArray, `fixtures`: List<FixtureExportInput>, `walls`: List<WallExportInput>, `deletedElementIds`: List<kotlin.ULong>, `movedElements`: List<ElementMoveInput>): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(IfcArException) { _status ->
    UniffiLib.INSTANCE.uniffi_ifc_ar_core_fn_func_export_combined_ifc_with_walls(
        FfiConverterByteArray.lower(`roomData`),FfiConverterSequenceTypeFixtureExportInput.lower(`fixtures`),FfiConverterSequenceTypeWallExportInput.lower(`walls`),FfiConverterSequenceULong.lower(`deletedElementIds`),FfiConverterSequenceTypeElementMoveInput.lower(`movedElements`),_status)
}
    )
    }
    

    @Throws(IfcArException::class) fun `parseAndExportGlb`(`data`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(IfcArException) { _status ->
    UniffiLib.INSTANCE.uniffi_ifc_ar_core_fn_func_parse_and_export_glb(
        FfiConverterByteArray.lower(`data`),_status)
}
    )
    }
    

    @Throws(IfcArException::class) fun `parseIfc`(`data`: kotlin.ByteArray): IfcModel {
            return FfiConverterTypeIfcModel.lift(
    uniffiRustCallWithError(IfcArException) { _status ->
    UniffiLib.INSTANCE.uniffi_ifc_ar_core_fn_func_parse_ifc(
        FfiConverterByteArray.lower(`data`),_status)
}
    )
    }
    


